Updates.
Maxcloud/Mushy pull request #79
Opened 2016-10-04 10:28 UTC by Savion

Refactored the rest of the mplew to pw for consistency.
Implemented Reward Points. (Although nothing related to Maple Rewards is implemented.)
Removed Wishlists entirely.
Implemented Favorites. You should be able to add/remove just fine. (Still have minor adjustment to show an item as already being a favorite, that will come later.)
Commented out the Unhandled Recv, as it seemed to pass everything through as unhandled even if it was handled.
Buying in the cash shop works, as well as putting the item from CSInventory to Character Inventory. (*Warning, you will have to make sure you have dumped your items for this to work; Currently, Mushy will require you to input your credentials to constants/ServerConfig.java to prevent a NPE during dumping.)

Added two SQL files for Flyway Migration, one just to add reward points field to accounts table and the other will add a favorites table.

2016-10-04 10:56 UTC, diamondo25 requested changes

2016-10-04 10:56 UTC, diamondo25 commented on src/client/MapleCharacter.java
> +				ps = con.prepareStatement("SELECT * FROM favorites WHERE `accountid` = ?");
Maybe somebody needs to specify formatting rules; this one is spaces and tabs combined

2016-10-04 10:56 UTC, diamondo25 commented on src/client/MapleCharacter.java
> +            ps = con.prepareStatement("UPDATE accounts SET `nxCredit` = ?, `ACash` = ?, `mPoints` = ?, `rPoints` = ?, `points` = ?, `vpoints` = ?, `dpoints` = ?, `epoints` = ? WHERE id = ?");
Using backticks is only required for reserved keywords (and using reserved keywords is bad programming to begin with).

2016-10-04 10:56 UTC, diamondo25 commented on src/client/MapleCharacter.java
> +                    ps = con.prepareStatement("INSERT INTO favorites(accountid, sn) VALUES(?, ?) ");
Prepare statement once, set values and execute in the loop, then close.

2016-10-04 10:56 UTC, diamondo25 commented on src/handling/world/CharacterTransfer.java
> +            partyid, messengerid, ACash, nxCredit, MaplePoints, RewardPoints,
Although MaplePoints is capitalized, I think its confusing to use CamelCase'd variable names.

2016-10-04 10:56 UTC, diamondo25 commented on src/handling/world/CharacterTransfer.java
> +		this.favorites = chr.getFavorites();
Indentation

2016-10-04 10:56 UTC, diamondo25 commented on src/handling/world/CharacterTransfer.java
> +        for (int i = 0; i < favoritesize; i++) {
No need to read the value and put it in scope:
```
for (int i = in.readShort(); i > 0; i--)
```

2016-10-04 11:05 UTC, Savion commented on src/client/MapleCharacter.java
> +				ps = con.prepareStatement("SELECT * FROM favorites WHERE `accountid` = ?");
Yea, I had issues with git earlier today and all of this went through notepad++ then back into an IDE. I thought I caught most of the whitespacing issues, but I guess not.

2016-10-04 11:08 UTC, diamondo25 commented on src/client/MapleCharacter.java
> +				ps = con.prepareStatement("SELECT * FROM favorites WHERE `accountid` = ?");
You could also start using auto format on save :)

2016-10-04 11:19 UTC, Savion commented on src/client/MapleCharacter.java
> +				ps = con.prepareStatement("SELECT * FROM favorites WHERE `accountid` = ?");
I shall download a plugin for that, good idea. :)

2016-10-04 11:21 UTC, Savion commented on src/client/MapleCharacter.java
> +            ps = con.prepareStatement("UPDATE accounts SET `nxCredit` = ?, `ACash` = ?, `mPoints` = ?, `rPoints` = ?, `points` = ?, `vpoints` = ?, `dpoints` = ?, `epoints` = ? WHERE id = ?");
Stuck with it for consistency, not too willing to do a rehaul such as that for now, though it'd be better to go back and completely revise them sometime later.

2016-10-04 11:21 UTC, Savion commented on src/handling/world/CharacterTransfer.java
> +            partyid, messengerid, ACash, nxCredit, MaplePoints, RewardPoints,
This has been since been corrected, thanks! I thought so, too, but again stuck with it for consistency.

2016-10-04 11:21 UTC, Savion commented on src/handling/world/CharacterTransfer.java
> +		this.favorites = chr.getFavorites();
This has been fixed, thanks!

2016-10-04 11:22 UTC, Savion commented on src/handling/world/CharacterTransfer.java
> +        for (int i = 0; i < favoritesize; i++) {
It was more so a la copy paste for CharacterTransfer, stuck with it for the consistency.

2016-10-04 11:24 UTC, Savion commented on src/client/MapleCharacter.java
> +                    ps = con.prepareStatement("INSERT INTO favorites(accountid, sn) VALUES(?, ?) ");
I was initially confused with this, but it does make sense to have the prepareStatement and close outside of the loop. I stuck with the same pattern among others in CharacterTransfer for the consistency for now, though.

2016-10-04 11:31 UTC, diamondo25 commented on src/client/MapleCharacter.java
> +                    ps = con.prepareStatement("INSERT INTO favorites(accountid, sn) VALUES(?, ?) ");
It does make sense; prepared statements are made for efficiency. If there's more spots that are using this kind of building queries, they all should be refactored.
These things could reduce the speed a lot.

2016-10-04 11:37 UTC, Fraysa commented on src/handling/world/CharacterTransfer.java
> +        for (int i = 0; i < favoritesize; i++) {
@diamondo25 I disagree, it's generally good for debugging purposes.

2016-10-04 11:58 UTC, diamondo25 commented on src/constants/ServerConfig.java
> -	public static String SQL_PASS = "Adminroot0829!";
gg

2016-10-04 19:48 UTC, Savion commented on src/constants/ServerConfig.java
> -	public static String SQL_PASS = "Adminroot0829!";
Tis but a scratch on a localhost db only, all good.

2016-10-05 01:16 UTC, barryanders commented
If someone would specify a preference for tabs or spaces (2 or 4), I'll go through and make them all the same.

2016-10-07 19:11 UTC, closed without merging